# -*- coding: utf-8 -*-
"""Kopie sešitu Model_1_Kotrys.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ApoaoU0ZNAa5rDjWCjtLSeh5q5QgBUwd
"""

from google.colab import drive
from typing import List
import numpy as np
import pandas as pd
import csv
from collections import defaultdict

print("Setup probehl v poradku.")

columns = defaultdict(list)
with open('drive/MyDrive/dataset/generated_quadruplexes.csv') as g4_csv:
    g4_reader = csv.reader(g4_csv, delimiter=',')
    with open('drive/MyDrive/dataset/converted_quadruplexes.csv', 'w') as g4mod_csv:
        g4_writer = csv.writer(g4mod_csv, delimiter = ',')
        line_count = 0 
        for row in g4_reader:
            if line_count == 0:
                row = ['']
                for i in range(30):
                    row.append('b{}' .format(i))
                row.append('g4')
                g4_writer.writerow(row)
                line_count += 1 
            else:
                sequences = row[1]
                for sequence in sequences:               
                    for base in sequence:
                        if base == 'G':
                            row.append(1)
                        elif base == 'C':
                            row.append(-1)
                        else:
                            row.append(0)
                row.pop(1)
                row.append(row[1])
                row.pop(1)
                g4_writer.writerow(row)
                converted = []
                line_count += 1

    print()
    print(f'Processed {line_count} lines.')
    g4mod_csv.close()

guanin_4 = pd.read_csv("drive/MyDrive/dataset/converted_quadruplexes.csv")
guanin_4.head()